version: '3.2'

services:

  mongo:
    image: mongo:4.1
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  node:
    image: 'node:8.12.0'
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command: "npm start"
    depends_on:
      - mongo

  nginx:
    command: nginx
    build:
      context: ./nginx
      dockerfile: DockerfileNginx
    ports:
      - '80:80'
    depends_on:
      - node
    volumes:
      - ./public:/code/static

  hive:
    image: hivemq/hivemq4
    ports:
      - "8080:8080"
      - "1883:1883"
      - "8000:8000"
    volumes:
      - ./hive_config.conf:/opt/hivemq-4.0.0/conf/config.xml